name: Build and Publish

on:
  push:
    branches:
      - main
    paths:
      - 'setup.py'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build package
        run: python -m build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
  create-draft-release:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - name: Create draft release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          tag_name: ''
          release_name: Draft Release for Main Branch
          draft: true
          prerelease: false
          body: |
            Changes since the last release:
            ${{ github.event.commits }}
